name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false 

      - name: Install and Build 🔧
        run: |
          npm install
          npm run-script build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build

# ----------------------------------------------------------
# CODE I WAS USING TO DEPLOY IT TO VPS
# ----------------------------------------------------------
# name: Deploy Prod

# on:
#   push:
#     branches: [ master ]
#   # pull_request:
#   #   branches: [ master ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x]

#     steps:
#     - uses: actions/checkout@v1

#     - name: Install dependencies and create build
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm i
#     - run: npm run build --if-present

#     - name: Copy repository contents via scp
#       uses: appleboy/scp-action@master
#       env:
#         HOST: ${{ secrets.HOST }}
#         USERNAME: ${{ secrets.USERNAME }}
#         PORT: ${{ secrets.PORT }}
#         KEY: ${{ secrets.SSHKEY }}
#       with:
#         source: "./build/"
#         target: "/home/amankori2307/Monopoly/prod/"

#     - name: Executing remote command
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         USERNAME: ${{ secrets.USERNAME }}
#         PORT: ${{ secrets.PORT }}
#         KEY: ${{ secrets.SSHKEY }}
#         script: ls ./Monopoly/prod/build
